steps:
  - label: ":package: Build image"
    key: build
    command:
      - "docker build -t ${CONTAINER_NAME} -f ./${CONTAINER_NAME}/Dockerfile ."
  - label: ":docker: Publish to docker hub"
    depends_on: build
    command:
      - "echo ${DOCKER_LOGIN_PASSWORD} | docker login -u ${DOCKER_LOGIN_USERNAME} --password-stdin"
      - "docker tag ${CONTAINER_NAME} tapendium/${BUILDKITE_TAG}"
      - "docker push tapendium/${BUILDKITE_TAG}"
