steps:
  - label: ":package: Build image"
    key: build
    command:
      - "docker build -t ${CONTAINER_NAME} -f ./${CONTAINER_NAME}/Dockerfile ."
  - label: ":docker: Publish to docker hub"
    depends_on: build
    command:
      - "docker tag ${CONTAINER_NAME}:latest tapendium/${CONTAINER_NAME}:latest"
      - "docker push tapendium/${CONTAINER_NAME}:latest"
    plugins:
      - docker-login#v2.0.1:
          username: tapendium
