steps:
  - label: ":docker: Publish to docker hub"
    commands:
      - echo c228c5fe-d0da-469e-b781-ad824d688872 | docker login -u lewisliew --password-stdin
    # env:
    #   - DOCKER_LOGIN_PASSWORD=c228c5fe-d0da-469e-b781-ad824d688872
    #   - DOCKER_LOGIN_USERNAME=lewisliew
    # plugins:
    #   - docker-login#v2.1.0:
    #       username: lewisliew
    #       password-env: DOCKER_LOGIN_PASSWORD
