steps:
  - label: ":docker: Publish to docker hub"
    plugins:
      - docker-login#v2.1.0:
          username: "${DOCKER_LOGIN_USERNAME}"
    # commands:
    #   - echo c228c5fe-d0da-469e-b781-ad824d688872 | docker login -u lewisliew --password-stdin
