steps:
  - label: ":package: Build image"
    key: build
    command:
      - "docker build -t ${CONTAINER_NAME}:{{matrix}}
        --build-arg TARGETPLATFORM={{matrix}}
        --platform linux/{{matrix}}
        -f ./${CONTAINER_NAME}/Dockerfile ."
    matrix:
      - arm64

  - label: ":docker: Publish to docker hub"
    key: publish
    depends_on: build
    command:
      - "docker tag ${CONTAINER_NAME}:{{matrix}}
        tapendium/${CONTAINER_NAME}:{{matrix}}"
      - "docker push tapendium/${CONTAINER_NAME}:{{matrix}}"
    matrix:
      - arm64
    plugins:
      - tapendium/1password-secrets#v1.1.0:
          env:
            BUILDKITE_PLUGIN_DOCKER_LOGIN_USERNAME:
              secret-uuid: zisch5odkndtzeb6pqupfazww4
              field: username
            DOCKER_LOGIN_PASSWORD:
              secret-uuid: zisch5odkndtzeb6pqupfazww4
              field: credential
      - docker-login#v2.1.0

  - label: ":docker::scroll: Create manifest"
    depends_on: publish
    command:
      - "docker manifest create
          tapendium/${IMAGE_TAG_NAME}
          tapendium/${CONTAINER_NAME}:$$ARM"
    env:
      ARM: arm64
