steps:
  - label: "lint Dockerfile pipeline"
    plugins:
      - docker#v3.13.0:
          image: hadolint/hadolint
          propagate-environment: true
          command: 
            - "./$CONTAINER_NAME/Dockerfile"
