steps:
  - label: "lint Dockerfile pipeline"
    plugins:
      - docker#v3.13.0:
          image: hadolint/hadolint
          propagate-environment: true
          command:
            - hadolint
            - "./${CONTAINER_NAME}/Dockerfile"
