steps:
  - label: "Triggering tests pipelines"
    plugins:
      - chronotc/monorepo-diff:
          diff: "git diff --name-only HEAD..main"
          watch:
            - path: cfnlint
              config:
                label: ":pipeline: Upload unit-test pipeline for cfnlint"
                command: buildkite-agent pipeline upload .buildkite/test.yml
                env:
                  - CONTAINER_NAME=cfnlint
  - label: "Triggering lint pipelines"
    plugins:
      - chronotc/monorepo-diff:
          diff: "git diff --name-only HEAD..main"
          watch:
            - path: cfnlint
              config:
                label: ":pipeline: Upload lint pipeline for cfnlint container"
                command: buildkite-agent pipeline upload .buildkite/lint.yml
                env:
                  - CONTAINER_NAME=cfnlint
