steps:
  - label: "Triggering lint pipelines"
    plugins:
      - chronotc/monorepo-diff:
          watch:
            - path: cfnlint
              config:
                label: ':pipeline: Upload lint pipeline for cfnlint container'
                command: echo "Changes detected!"
                env:
                  - MODULE=cfnlint
