docker-credentials: &docker-credentials
  tapendium/1password-secrets#v1.1.0:
    env:
      DOCKER_LOGIN_PASSWORD:
        secret-uuid: zisch5odkndtzeb6pqupfazww4
        field: credential
      DOCKER_LOGIN_USERNAME:
        secret-uuid: zisch5odkndtzeb6pqupfazww4
        field: username

steps:
  - label: "Triggering tests pipelines"
    plugins:
      - chronotc/monorepo-diff#v2.3.0:
          diff: "git diff --name-only HEAD..origin/main"
          watch:
            - path: cfn-lint
              config:
                label: ":pipeline: Upload unit-test pipeline for cfn-lint"
                command: buildkite-agent pipeline upload .buildkite/test.yml
                env:
                  - CONTAINER_NAME=cfn-lint
  - label: "Triggering lint pipelines"
    plugins:
      - chronotc/monorepo-diff#v2.3.0:
          diff: "git diff --name-only HEAD..origin/main"
          watch:
            - path: cfn-lint
              config:
                label: ":pipeline: Upload lint pipeline for cfn-lint container"
                command: buildkite-agent pipeline upload .buildkite/lint.yml
                env:
                  - CONTAINER_NAME=cfn-lint
  - label: ":pipeline: test docker login"
    commands: 
      - buildkite-agent pipeline upload .buildkite/deploytest.yml
    env:
      - CONTAINER_NAME=cfn-lint
      - DOCKER_LOGIN_PASSWORD
      - DOCKER_LOGIN_USERNAME
    plugins:
      - *docker-credentials
