steps:
  - label: "Lint Dockerfiles"
    plugins:
      - chronotc/monorepo-diff:
          watch:
            - path: cfn-lint
              config:
                label: ':pipeline: Upload lint pipeline for cfn-lint container'
                command: echo "Changes detected!"
