steps:
  - label: ":docker: Load Docker hub credentials"
    plugins:
      - tapendium/1password-secrets#v1.1.0:
          env:
            DOCKER_LOGIN_PASSWORD:
              secret-uuid: zisch5odkndtzeb6pqupfazww4
              field: credential
            DOCKER_LOGIN_USERNAME:
              secret-uuid: zisch5odkndtzeb6pqupfazww4
              field: username
  - label: ":pipeline: triggering deploy pipelines"
    if: build.tag !~ /^skip:/
    commands: 
      - export CONTAINER_NAME=$(echo ${BUILDKITE_TAG} | cut -f1 -d":")
      - buildkite-agent pipeline upload .buildkite/deploy.yml
    env:
      - DOCKER_LOGIN_PASSWORD
      - DOCKER_LOGIN_USERNAME
  - label: ":pipeline: triggering custom deploy pipelines"
    if: build.tag =~ /^skip:\d+\.\d+\.\d+$/
    command: echo "I have a custom deployment pipeline"
