steps:
  - label: "Build image"
    key: build
    command:
      - "docker build -t ${CONTAINER_NAME} -f ./${CONTAINER_NAME}/Dockerfile ."
  - label: "list images"
    depends_on: build
    command:
      - "docker image ls"
  - label: "Dockerfile unit-test container"
    depends_on: build
    command:
      - "curl -LO https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-arm64"
      - "chmod +x container-structure-test-linux-arm64"
      - "mkdir -p $HOME/bin"
      - "export PATH=$PATH:$HOME/bin"
      - "mv container-structure-test-linux-arm64 $HOME/bin/container-structure-test"
      - "container-structure-test test --image ${CONTAINER_NAME} --config /currentdir/app/${CONTAINER_NAME}/unit-test.yml"
        # - label: "unit tests"
        #   depends_on: build
        #   command:
        #     - "docker run --rm -i --platform linux/arm64/v8 -v ${BUILDKITE_BUILD_CHECKOUT_PATH}:/currentdir/app -v /var/run/docker.sock:/var/run/docker.sock emanlx/container-structure-test:v1.9.1-alpine test --image ${CONTAINER_NAME} --config /currentdir/app/${CONTAINER_NAME}/unit-test.yml"
        #  - label: "Dockerfile unit-test container"
        #    depends_on: build
        #    plugins:
        #      - docker#v3.13.0:
        #          image: "gcr.io/gcp-runtimes/container-structure-test:latest"
        #          propagate-environment: true
        #          volumes:
        #            - "${BUILDKITE_BUILD_CHECKOUT_PATH}:/currentdir/app"
        #            - "/var/run/docker.sock:/var/run/docker.sock"
        #          command:
        #            - "test"
        #            - "--image"
        #            - "${CONTAINER_NAME}"
        #            - "--config"
        #            - "/currentdir/app/${CONTAINER_NAME}/unit-test.yml"
