steps:
  - label: "Dockerfile unit-test pipeline"
    command:
      - "docker build -t ${CONTAINER_NAME} -f ./${CONTAINER_NAME}/Dockerfile ."
    plugins:
      - docker#v3.13.0:
          image: gcr.io/gcp-runtimes/container-structure-test:latest
          propagate-environment: true
          volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
          command: 
            - test --image ${CONTAINER_NAME} --config ./${CONTAINER_NAME}/unit-test.yml
