steps:
  - label: "Dockerfile unit-test pipeline"
    command:
      - "docker build -t ${CONTAINER_NAME} -f ./${CONTAINER_NAME}/Dockerfile ."
      - >-
        "docker run --rm -i
        -v /workdir:/workdir
        -v /var/run/docker.sock:/var/run/docker.sock
        --workdir /workdir
        gcr.io/gcp-runtimes/container-structure-test:latest
        test --image ${CONTAINER_NAME}
        --config /workdir/${CONTAINER_NAME}/unit-test.yml"
