steps:
  - label: "Build image"
    key: build
    command:
      - "docker build -t ${CONTAINER_NAME} -f ./${CONTAINER_NAME}/Dockerfile ."
  - label: "list images"
    depends_on: build
    command:
      - "docker image ls"
  - label: "Dockerfile unit-test container"
    depends_on: build
    command:
      - "curl -LO https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-arm64"
      - "chmod +x container-structure-test-linux-arm64"
      - "mkdir -p $HOME/bin"
      - "export PATH=$PATH:$HOME/bin"
      - "mv container-structure-test-linux-arm64 $HOME/bin/container-structure-test"
      - "container-structure-test test --image ${CONTAINER_NAME} --config $(pwd)/${CONTAINER_NAME}/unit-test.yml"
